swagger: '2.0'
info:
  description: >
    This is a sample swagger file to explore some of the Synology Web APIs.
    [Generate your own swagger file](https://github.com/mikespub/synology)


    If you want to try this out on your own Synology, this requires adding
    a rest.php file in the base directory of your Web Station to act as a
    gateway to the actual Synology Web APIs.


    Except for SYNO.API.Info query, most API calls assume that you have
    logged in first via SYNO.API.Auth, and received a session id (sid).
    You will need to update the default value of the _sid parameter below
    in your swagger file so that all API calls can use the right value.


    There are many versions of the swagger file available, one using short
    urls with query parameters, and the other specifying the complete path
    including the 4 standard parameters for each API method. Any special
    additional parameters needed for a particular API method are not taken
    into account here (except for login).

  version: 1.0.0
  title: Synology Web API Explorer
  contact:
    url: 'https://github.com/mikespub/synology/issues'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
host: diskstation
basePath: /rest.php
schemes:
  - http
securityDefinitions:
  query_sid:
    type: apiKey
    name: _sid
    in: query
consumes:
  - application/json
  - text/plain
produces:
  - application/json
  - text/plain
definitions:
  NormalResponse:
    type: object
    properties:
      success:
        type: boolean
        description: '"true" when the request finishes successfully, "false" when the request fails with an error code.'
      data:
        type: object
        description: The data object contains all the response information described in each method.
      error:
        type: object
        properties:
          code:
            type: integer
            description: An integer number error code will be returned when a request fails.
          errors:
            type: array
            items:
              type: object
paths:
  /SYNO.API.Info/v1/query:
    get:
      tags:
        - API
      summary: Return query for SYNO.API.Info
      operationId: API_Info_query
      parameters:
        - in: query
          name: query
          description: Requested API information
          required: true
          type: string
          default: all
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
  /SYNO.API.Auth/v4/login:
    get:
      tags:
        - API
      summary: Return login for SYNO.API.Auth
      operationId: API_Auth_login
      parameters:
        - in: query
          name: account
          description: Username
          required: false
          type: string
          default: username
        - in: query
          name: passwd
          description: Password
          required: false
          type: string
          default: passwd
        - in: query
          name: session
          description: Session Name
          required: true
          type: string
          default: DownloadStation
        - in: query
          name: format
          description: Format (cookie or sid)
          required: false
          type: string
          default: sid
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
  /SYNO.API.Auth/v4/logout:
    get:
      tags:
        - API
      summary: Return logout for SYNO.API.Auth
      operationId: API_Auth_logout
      parameters:
        - in: query
          name: session
          description: Session Name
          required: true
          type: string
          default: DownloadStation
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Channel/v1/list:
    get:
      tags:
        - DTV.Channel
      summary: Return list for SYNO.DTV.Channel
      operationId: Channel_list
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Channel/v1/getinfo:
    get:
      tags:
        - DTV.Channel
      summary: Return getinfo for SYNO.DTV.Channel
      operationId: Channel_getinfo
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Channel/v1/delete_all_channels:
    get:
      tags:
        - DTV.Channel
      summary: Return delete_all_channels for SYNO.DTV.Channel
      operationId: Channel_delete_all_channels
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Channel/v1/edit:
    get:
      tags:
        - DTV.Channel
      summary: Return edit for SYNO.DTV.Channel
      operationId: Channel_edit
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.ChannelScan/v1/getcountry:
    get:
      tags:
        - DTV.ChannelScan
      summary: Return getcountry for SYNO.DTV.ChannelScan
      operationId: ChannelScan_getcountry
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.ChannelScan/v1/getregion:
    get:
      tags:
        - DTV.ChannelScan
      summary: Return getregion for SYNO.DTV.ChannelScan
      operationId: ChannelScan_getregion
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.ChannelScan/v1/getconfig:
    get:
      tags:
        - DTV.ChannelScan
      summary: Return getconfig for SYNO.DTV.ChannelScan
      operationId: ChannelScan_getconfig
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.ChannelScan/v1/start:
    get:
      tags:
        - DTV.ChannelScan
      summary: Return start for SYNO.DTV.ChannelScan
      operationId: ChannelScan_start
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.ChannelScan/v1/stop:
    get:
      tags:
        - DTV.ChannelScan
      summary: Return stop for SYNO.DTV.ChannelScan
      operationId: ChannelScan_stop
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.ChannelScan/v1/status:
    get:
      tags:
        - DTV.ChannelScan
      summary: Return status for SYNO.DTV.ChannelScan
      operationId: ChannelScan_status
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Controller/v1/getchannel:
    get:
      tags:
        - DTV.Controller
      summary: Return getchannel for SYNO.DTV.Controller
      operationId: Controller_getchannel
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Controller/v1/setchannel:
    get:
      tags:
        - DTV.Controller
      summary: Return setchannel for SYNO.DTV.Controller
      operationId: Controller_setchannel
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Program/v1/list:
    get:
      tags:
        - DTV.Program
      summary: Return list for SYNO.DTV.Program
      operationId: Program_list
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Program/v1/search:
    get:
      tags:
        - DTV.Program
      summary: Return search for SYNO.DTV.Program
      operationId: Program_search
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Program/v1/update:
    get:
      tags:
        - DTV.Program
      summary: Return update for SYNO.DTV.Program
      operationId: Program_update
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Schedule/v1/list:
    get:
      tags:
        - DTV.Schedule
      summary: Return list for SYNO.DTV.Schedule
      operationId: Schedule_list
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Schedule/v1/create:
    get:
      tags:
        - DTV.Schedule
      summary: Return create for SYNO.DTV.Schedule
      operationId: Schedule_create
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Schedule/v1/delete:
    get:
      tags:
        - DTV.Schedule
      summary: Return delete for SYNO.DTV.Schedule
      operationId: Schedule_delete
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Schedule/v1/delete_passed:
    get:
      tags:
        - DTV.Schedule
      summary: Return delete_passed for SYNO.DTV.Schedule
      operationId: Schedule_delete_passed
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Schedule/v1/create_repeat:
    get:
      tags:
        - DTV.Schedule
      summary: Return create_repeat for SYNO.DTV.Schedule
      operationId: Schedule_create_repeat
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Schedule/v1/getinfo_repeat:
    get:
      tags:
        - DTV.Schedule
      summary: Return getinfo_repeat for SYNO.DTV.Schedule
      operationId: Schedule_getinfo_repeat
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Schedule/v1/edit_repeat:
    get:
      tags:
        - DTV.Schedule
      summary: Return edit_repeat for SYNO.DTV.Schedule
      operationId: Schedule_edit_repeat
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Schedule/v1/delete_repeat:
    get:
      tags:
        - DTV.Schedule
      summary: Return delete_repeat for SYNO.DTV.Schedule
      operationId: Schedule_delete_repeat
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Schedule/v1/getinfo_userdefine:
    get:
      tags:
        - DTV.Schedule
      summary: Return getinfo_userdefine for SYNO.DTV.Schedule
      operationId: Schedule_getinfo_userdefine
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Schedule/v1/create_userdefine:
    get:
      tags:
        - DTV.Schedule
      summary: Return create_userdefine for SYNO.DTV.Schedule
      operationId: Schedule_create_userdefine
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Schedule/v1/edit_userdefine:
    get:
      tags:
        - DTV.Schedule
      summary: Return edit_userdefine for SYNO.DTV.Schedule
      operationId: Schedule_edit_userdefine
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Schedule/v1/delete_userdefine:
    get:
      tags:
        - DTV.Schedule
      summary: Return delete_userdefine for SYNO.DTV.Schedule
      operationId: Schedule_delete_userdefine
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Statistic/v1/getinfo:
    get:
      tags:
        - DTV.Statistic
      summary: Return getinfo for SYNO.DTV.Statistic
      operationId: Statistic_getinfo
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Streaming/v1/open:
    get:
      tags:
        - DTV.Streaming
      summary: Return open for SYNO.DTV.Streaming
      operationId: Streaming_open
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Streaming/v1/stream:
    get:
      tags:
        - DTV.Streaming
      summary: Return stream for SYNO.DTV.Streaming
      operationId: Streaming_stream
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Streaming/v1/close:
    get:
      tags:
        - DTV.Streaming
      summary: Return close for SYNO.DTV.Streaming
      operationId: Streaming_close
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Tuner/v1/list:
    get:
      tags:
        - DTV.Tuner
      summary: Return list for SYNO.DTV.Tuner
      operationId: Tuner_list
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DTV.Tuner/v1/getinfo:
    get:
      tags:
        - DTV.Tuner
      summary: Return getinfo for SYNO.DTV.Tuner
      operationId: Tuner_getinfo
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
