openapi: 3.0.3
info:
  description: >
    This is a sample OpenAPI file to explore some of the Synology Web APIs.
    [Generate your own OpenAPI file](https://github.com/mikespub/synology)


    If you want to try this out on your own Synology, this requires adding
    a rest.php file in the base directory of your Web Station to act as a
    gateway to the actual Synology Web APIs.


    Except for SYNO.API.Info query, most API calls assume that you have
    logged in first via SYNO.API.Auth, and received a session id (sid).
    You will need to update the default value of the _sid parameter below
    in your OpenAPI file so that all API calls can use the right value.


    There are many versions of the OpenAPI file available, one using short
    urls with query parameters, and the other specifying the complete path
    including the 4 standard parameters for each API method. Any special
    additional parameters needed for a particular API method are not taken
    into account here (except for login).

  version: 3.0.0
  title: Synology Web API Explorer
  contact:
    url: https://github.com/mikespub/synology/issues
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: '{scheme}://{hostname}/{base}'
    variables:
      scheme:
        default: http
        enum:
          - http
          - https
      hostname:
        default: diskstation
      base:
        default: rest.php
paths:
  /SYNO.API.Info/v1/query:
    get:
      tags:
        - API
      summary: Return query for SYNO.API.Info
      operationId: API_Info_query
      parameters:
        - in: query
          name: query
          description: Requested API information
          required: true
          schema:
            type: string
            default: all
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
  /SYNO.API.Auth/v6/login:
    get:
      tags:
        - API
      summary: Return login for SYNO.API.Auth
      operationId: API_Auth_login
      parameters:
        - in: query
          name: account
          description: Username
          required: false
          schema:
            type: string
            default: username
        - in: query
          name: passwd
          description: Password
          required: false
          schema:
            type: string
            default: passwd
        - in: query
          name: session
          description: Session Name
          required: true
          schema:
            type: string
            default: DownloadStation
        - in: query
          name: format
          description: Format (cookie or sid)
          required: false
          schema:
            type: string
            default: sid
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
  /SYNO.API.Auth/v6/logout:
    get:
      tags:
        - API
      summary: Return logout for SYNO.API.Auth
      operationId: API_Auth_logout
      parameters:
        - in: query
          name: session
          description: Session Name
          required: true
          schema:
            type: string
            default: DownloadStation
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
  /SYNO.Lunbackup/v1/rtor_name_get:
    get:
      tags:
        - Lunbackup.
      summary: Return rtor_name_get for SYNO.Lunbackup
      operationId: _rtor_name_get
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
  /SYNO.Lunbackup/v1/space_check:
    get:
      tags:
        - Lunbackup.
      summary: Return space_check for SYNO.Lunbackup
      operationId: _space_check
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
  /SYNO.Lunbackup/v1/dir_check:
    get:
      tags:
        - Lunbackup.
      summary: Return dir_check for SYNO.Lunbackup
      operationId: _dir_check
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
  /SYNO.Lunbackup/v1/task_owner_check:
    get:
      tags:
        - Lunbackup.
      summary: Return task_owner_check for SYNO.Lunbackup
      operationId: _task_owner_check
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
  /SYNO.Lunbackup/v1/task_folder_enum:
    get:
      tags:
        - Lunbackup.
      summary: Return task_folder_enum for SYNO.Lunbackup
      operationId: _task_folder_enum
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
  /SYNO.Lunbackup/v1/file_config_get:
    get:
      tags:
        - Lunbackup.
      summary: Return file_config_get for SYNO.Lunbackup
      operationId: _file_config_get
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
  /SYNO.Lunbackup/v1/file_config_set:
    get:
      tags:
        - Lunbackup.
      summary: Return file_config_set for SYNO.Lunbackup
      operationId: _file_config_set
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
  /SYNO.Lunbackup/v1/cksum_do:
    get:
      tags:
        - Lunbackup.
      summary: Return cksum_do for SYNO.Lunbackup
      operationId: _cksum_do
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
  /SYNO.Lunbackup/v1/cksum_gen:
    get:
      tags:
        - Lunbackup.
      summary: Return cksum_gen for SYNO.Lunbackup
      operationId: _cksum_gen
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
  /SYNO.Lunbackup/v1/cksum_status_get:
    get:
      tags:
        - Lunbackup.
      summary: Return cksum_status_get for SYNO.Lunbackup
      operationId: _cksum_status_get
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
components:
  securitySchemes:
    query_sid:
      type: apiKey
      name: _sid
      in: query
  schemas:
    NormalResponse:
      type: object
      properties:
        success:
          type: boolean
          description: '"true" when the request finishes successfully, "false" when the request fails with an error code.'
        data:
          type: object
          description: The data object contains all the response information described in each method.
        error:
          type: object
          properties:
            code:
              type: integer
              description: An integer number error code will be returned when a request fails.
            errors:
              type: array
              items:
                type: object
