openapi: 3.0.3
info:
  description: >
    This is a sample OpenAPI file to explore some of the Synology Web APIs.
    [Generate your own OpenAPI file](https://github.com/mikespub/synology)


    If you want to try this out on your own Synology, this requires adding
    a rest.php file in the base directory of your Web Station to act as a
    gateway to the actual Synology Web APIs.


    Except for SYNO.API.Info query, most API calls assume that you have
    logged in first via SYNO.API.Auth, and received a session id (sid).
    You will need to update the default value of the _sid parameter below
    in your OpenAPI file so that all API calls can use the right value.


    There are many versions of the OpenAPI file available, one using short
    urls with query parameters, and the other specifying the complete path
    including the 4 standard parameters for each API method. Any special
    additional parameters needed for a particular API method are not taken
    into account here (except for login).

  version: 3.0.0
  title: Synology Web API Explorer
  contact:
    url: https://github.com/mikespub/synology/issues
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: '{scheme}://{hostname}/{base}'
    variables:
      scheme:
        default: http
        enum:
          - http
          - https
      hostname:
        default: diskstation
      base:
        default: rest.php
paths:
  /SYNO.API.Info/v1/query:
    get:
      tags:
        - API
      summary: Return query for SYNO.API.Info
      operationId: API_Info_query
      parameters:
        - in: query
          name: query
          description: Requested API information
          required: true
          schema:
            type: string
            default: all
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
  /SYNO.API.Auth/v6/login:
    get:
      tags:
        - API
      summary: Return login for SYNO.API.Auth
      operationId: API_Auth_login
      parameters:
        - in: query
          name: account
          description: Username
          required: false
          schema:
            type: string
            default: username
        - in: query
          name: passwd
          description: Password
          required: false
          schema:
            type: string
            default: passwd
        - in: query
          name: session
          description: Session Name
          required: true
          schema:
            type: string
            default: DownloadStation
        - in: query
          name: format
          description: Format (cookie or sid)
          required: false
          schema:
            type: string
            default: sid
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
  /SYNO.API.Auth/v6/logout:
    get:
      tags:
        - API
      summary: Return logout for SYNO.API.Auth
      operationId: API_Auth_logout
      parameters:
        - in: query
          name: session
          description: Session Name
          required: true
          schema:
            type: string
            default: DownloadStation
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
  /SYNO.Network.DHCPServer/v4/get:
    get:
      tags:
        - Network.DHCPServer
      summary: Return get for SYNO.Network.DHCPServer
      operationId: DHCPServer_get
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.Network.DHCPServer.ClientList/v2/list:
    get:
      tags:
        - Network.DHCPServer
      summary: Return list for SYNO.Network.DHCPServer.ClientList
      operationId: DHCPServer_ClientList_list
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.Network.DHCPServer.PXE/v1/get:
    get:
      tags:
        - Network.DHCPServer
      summary: Return get for SYNO.Network.DHCPServer.PXE
      operationId: DHCPServer_PXE_get
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Network.DHCPServer.PXE_GetResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.Network.DHCPServer.PXE/v1/set:
    get:
      tags:
        - Network.DHCPServer
      summary: Return set for SYNO.Network.DHCPServer.PXE
      operationId: DHCPServer_PXE_set
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.Network.DHCPServer.Reservation/v3/get:
    get:
      tags:
        - Network.DHCPServer
      summary: Return get for SYNO.Network.DHCPServer.Reservation
      operationId: DHCPServer_Reservation_get
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.Network.DHCPServer.Vendor/v1/get:
    get:
      tags:
        - Network.DHCPServer
      summary: Return get for SYNO.Network.DHCPServer.Vendor
      operationId: DHCPServer_Vendor_get
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Network.DHCPServer.Vendor_GetResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.Network.DHCPServer.Vendor/v1/set:
    get:
      tags:
        - Network.DHCPServer
      summary: Return set for SYNO.Network.DHCPServer.Vendor
      operationId: DHCPServer_Vendor_set
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.Network.DHCPServer.WPAD/v1/get:
    get:
      tags:
        - Network.DHCPServer
      summary: Return get for SYNO.Network.DHCPServer.WPAD
      operationId: DHCPServer_WPAD_get
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.Network.DHCPServer.WPAD/v1/set:
    get:
      tags:
        - Network.DHCPServer
      summary: Return set for SYNO.Network.DHCPServer.WPAD
      operationId: DHCPServer_WPAD_set
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
components:
  securitySchemes:
    query_sid:
      type: apiKey
      name: _sid
      in: query
  schemas:
    NormalResponse:
      type: object
      properties:
        success:
          type: boolean
          description: '"true" when the request finishes successfully, "false" when the request fails with an error code.'
        data:
          type: object
          description: The data object contains all the response information described in each method.
        error:
          type: object
          properties:
            code:
              type: integer
              description: An integer number error code will be returned when a request fails.
            errors:
              type: array
              items:
                type: object
    Network.DHCPServer.PXE_GetResponse:
      type: object
      properties:
        success:
          type: boolean
          description: '"true" when the request finishes successfully, "false" when the request fails with an error code.'
        data:
          $ref: '../schemas/object.json'
        error:
          type: object
          properties:
            code:
              type: integer
              description: An integer number error code will be returned when a request fails.
            errors:
              type: array
              items:
                type: object
    Network.DHCPServer.Vendor_GetResponse:
      type: object
      properties:
        success:
          type: boolean
          description: '"true" when the request finishes successfully, "false" when the request fails with an error code.'
        data:
          $ref: '../schemas/object.json'
        error:
          type: object
          properties:
            code:
              type: integer
              description: An integer number error code will be returned when a request fails.
            errors:
              type: array
              items:
                type: object
