openapi: 3.0.3
info:
  description: >
    This is a sample OpenAPI file to explore some of the Synology Web APIs.
    [Generate your own OpenAPI file](https://github.com/mikespub/synology)


    If you want to try this out on your own Synology, this requires adding
    a rest.php file in the base directory of your Web Station to act as a
    gateway to the actual Synology Web APIs.


    Except for SYNO.API.Info query, most API calls assume that you have
    logged in first via SYNO.API.Auth, and received a session id (sid).
    You will need to update the default value of the _sid parameter below
    in your OpenAPI file so that all API calls can use the right value.


    There are many versions of the OpenAPI file available, one using short
    urls with query parameters, and the other specifying the complete path
    including the 4 standard parameters for each API method. Any special
    additional parameters needed for a particular API method are not taken
    into account here (except for login).

  version: 3.0.0
  title: Synology Web API Explorer
  contact:
    url: https://github.com/mikespub/synology/issues
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: '{scheme}://{hostname}/{base}'
    variables:
      scheme:
        default: http
        enum:
          - http
          - https
      hostname:
        default: diskstation
      base:
        default: rest.php
paths:
  /SYNO.API.Info/v1/query:
    get:
      tags:
        - API
      summary: Return query for SYNO.API.Info
      operationId: API_Info_query
      parameters:
        - in: query
          name: query
          description: Requested API information
          required: true
          schema:
            type: string
            default: all
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
  /SYNO.API.Auth/v6/login:
    get:
      tags:
        - API
      summary: Return login for SYNO.API.Auth
      operationId: API_Auth_login
      parameters:
        - in: query
          name: account
          description: Username
          required: false
          schema:
            type: string
            default: username
        - in: query
          name: passwd
          description: Password
          required: false
          schema:
            type: string
            default: passwd
        - in: query
          name: session
          description: Session Name
          required: true
          schema:
            type: string
            default: DownloadStation
        - in: query
          name: format
          description: Format (cookie or sid)
          required: false
          schema:
            type: string
            default: sid
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
  /SYNO.API.Auth/v6/logout:
    get:
      tags:
        - API
      summary: Return logout for SYNO.API.Auth
      operationId: API_Auth_logout
      parameters:
        - in: query
          name: session
          description: Session Name
          required: true
          schema:
            type: string
            default: DownloadStation
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
  /SYNO.SecurityAdvisor.Conf/v1/set:
    get:
      tags:
        - SecurityAdvisor.Conf
      summary: Return set for SYNO.SecurityAdvisor.Conf
      operationId: Conf_set
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.SecurityAdvisor.Conf/v1/get:
    get:
      tags:
        - SecurityAdvisor.Conf
      summary: Return get for SYNO.SecurityAdvisor.Conf
      operationId: Conf_get
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityAdvisor.Conf_GetResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.SecurityAdvisor.Conf/v1/init:
    get:
      tags:
        - SecurityAdvisor.Conf
      summary: Return init for SYNO.SecurityAdvisor.Conf
      operationId: Conf_init
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.SecurityAdvisor.Conf.Checklist/v1/list:
    get:
      tags:
        - SecurityAdvisor.Conf
      summary: Return list for SYNO.SecurityAdvisor.Conf.Checklist
      operationId: Conf_Checklist_list
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.SecurityAdvisor.Conf.Checklist/v1/set:
    get:
      tags:
        - SecurityAdvisor.Conf
      summary: Return set for SYNO.SecurityAdvisor.Conf.Checklist
      operationId: Conf_Checklist_set
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.SecurityAdvisor.Conf.Checklist.Alert/v1/set:
    get:
      tags:
        - SecurityAdvisor.Conf
      summary: Return set for SYNO.SecurityAdvisor.Conf.Checklist.Alert
      operationId: Conf_Checklist_Alert_set
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.SecurityAdvisor.Conf.Location/v1/get:
    get:
      tags:
        - SecurityAdvisor.Conf
      summary: Return get for SYNO.SecurityAdvisor.Conf.Location
      operationId: Conf_Location_get
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.SecurityAdvisor.LoginActivity/v1/list:
    get:
      tags:
        - SecurityAdvisor.LoginActivity
      summary: Return list for SYNO.SecurityAdvisor.LoginActivity
      operationId: LoginActivity_list
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityAdvisor.LoginActivity_ListResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.SecurityAdvisor.LoginActivity.User/v1/get:
    get:
      tags:
        - SecurityAdvisor.LoginActivity
      summary: Return get for SYNO.SecurityAdvisor.LoginActivity.User
      operationId: LoginActivity_User_get
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityAdvisor.LoginActivity.User_GetResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.SecurityAdvisor.Report/v1/list:
    get:
      tags:
        - SecurityAdvisor.Report
      summary: Return list for SYNO.SecurityAdvisor.Report
      operationId: Report_list
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.SecurityAdvisor.Report/v1/create:
    get:
      tags:
        - SecurityAdvisor.Report
      summary: Return create for SYNO.SecurityAdvisor.Report
      operationId: Report_create
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
  /SYNO.SecurityAdvisor.Report.HTML/v1/open:
    get:
      tags:
        - SecurityAdvisor.Report
      summary: Return open for SYNO.SecurityAdvisor.Report.HTML
      operationId: Report_HTML_open
      responses:
        '200':
          description: Normal Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalResponse'
        default:
          description: Abnormal Response
          content:
            application/json:
              schema:
                type: object
      security:
        - query_sid: []
      #parameters:
components:
  securitySchemes:
    query_sid:
      type: apiKey
      name: _sid
      in: query
  schemas:
    NormalResponse:
      type: object
      properties:
        success:
          type: boolean
          description: '"true" when the request finishes successfully, "false" when the request fails with an error code.'
        data:
          type: object
          description: The data object contains all the response information described in each method.
        error:
          type: object
          properties:
            code:
              type: integer
              description: An integer number error code will be returned when a request fails.
            errors:
              type: array
              items:
                type: object
    SecurityAdvisor.Conf_GetResponse:
      type: object
      properties:
        success:
          type: boolean
          description: '"true" when the request finishes successfully, "false" when the request fails with an error code.'
        data:
          $ref: '../schemas/../schemas/object.json'
        error:
          type: object
          properties:
            code:
              type: integer
              description: An integer number error code will be returned when a request fails.
            errors:
              type: array
              items:
                type: object
    SecurityAdvisor.LoginActivity_ListResponse:
      type: object
      properties:
        success:
          type: boolean
          description: '"true" when the request finishes successfully, "false" when the request fails with an error code.'
        data:
          $ref: '../schemas/../schemas/object.json'
        error:
          type: object
          properties:
            code:
              type: integer
              description: An integer number error code will be returned when a request fails.
            errors:
              type: array
              items:
                type: object
    SecurityAdvisor.LoginActivity.User_GetResponse:
      type: object
      properties:
        success:
          type: boolean
          description: '"true" when the request finishes successfully, "false" when the request fails with an error code.'
        data:
          $ref: '../schemas/../schemas/object.json'
        error:
          type: object
          properties:
            code:
              type: integer
              description: An integer number error code will be returned when a request fails.
            errors:
              type: array
              items:
                type: object
