swagger: '2.0'
info:
  description: >
    This is a sample swagger file to explore some of the Synology Web APIs.
    [Generate your own swagger file](https://github.com/mikespub/synology)


    If you want to try this out on your own Synology, this requires adding
    a rest.php file in the base directory of your Web Station to act as a
    gateway to the actual Synology Web APIs.


    Except for SYNO.API.Info query, most API calls assume that you have
    logged in first via SYNO.API.Auth, and received a session id (sid).
    You will need to update the default value of the _sid parameter below
    in your swagger file so that all API calls can use the right value.


    There are many versions of the swagger file available, one using short
    urls with query parameters, and the other specifying the complete path
    including the 4 standard parameters for each API method. Any special
    additional parameters needed for a particular API method are not taken
    into account here (except for login).

  version: 1.0.0
  title: Synology Web API Explorer
  contact:
    url: 'https://github.com/mikespub/synology/issues'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
host: diskstation
basePath: /rest.php
schemes:
  - http
securityDefinitions:
  query_sid:
    type: apiKey
    name: _sid
    in: query
consumes:
  - application/json
  - text/plain
produces:
  - application/json
  - text/plain
definitions:
  NormalResponse:
    type: object
    properties:
      success:
        type: boolean
        description: '"true" when the request finishes successfully, "false" when the request fails with an error code.'
      data:
        type: object
        description: The data object contains all the response information described in each method.
      error:
        type: object
        properties:
          code:
            type: integer
            description: An integer number error code will be returned when a request fails.
          errors:
            type: array
            items:
              type: object
paths:
  /SYNO.API.Info/v1/query:
    get:
      tags:
        - API
      summary: Return query for SYNO.API.Info
      operationId: API_Info_query
      parameters:
        - in: query
          name: query
          description: Requested API information
          required: true
          type: string
          default: all
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
  /SYNO.API.Auth/v4/login:
    get:
      tags:
        - API
      summary: Return login for SYNO.API.Auth
      operationId: API_Auth_login
      parameters:
        - in: query
          name: account
          description: Username
          required: false
          type: string
          default: username
        - in: query
          name: passwd
          description: Password
          required: false
          type: string
          default: passwd
        - in: query
          name: session
          description: Session Name
          required: true
          type: string
          default: DownloadStation
        - in: query
          name: format
          description: Format (cookie or sid)
          required: false
          type: string
          default: sid
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
  /SYNO.API.Auth/v4/logout:
    get:
      tags:
        - API
      summary: Return logout for SYNO.API.Auth
      operationId: API_Auth_logout
      parameters:
        - in: query
          name: session
          description: Session Name
          required: true
          type: string
          default: DownloadStation
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node/v1/info:
    get:
      tags:
        - DR.Node
      summary: Return info for SYNO.DR.Node
      operationId: Node_info
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node/v1/test_sync_speed:
    get:
      tags:
        - DR.Node
      summary: Return test_sync_speed for SYNO.DR.Node
      operationId: Node_test_sync_speed
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node/v1/test_download_speed:
    get:
      tags:
        - DR.Node
      summary: Return test_download_speed for SYNO.DR.Node
      operationId: Node_test_download_speed
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node/v1/test_privilege:
    get:
      tags:
        - DR.Node
      summary: Return test_privilege for SYNO.DR.Node
      operationId: Node_test_privilege
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node/v1/test_connection:
    get:
      tags:
        - DR.Node
      summary: Return test_connection for SYNO.DR.Node
      operationId: Node_test_connection
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node.Credential/v1/create:
    get:
      tags:
        - DR.Node
      summary: Return create for SYNO.DR.Node.Credential
      operationId: Node_Credential_create
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node.Credential/v1/set:
    get:
      tags:
        - DR.Node
      summary: Return set for SYNO.DR.Node.Credential
      operationId: Node_Credential_set
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node.Credential/v1/get:
    get:
      tags:
        - DR.Node
      summary: Return get for SYNO.DR.Node.Credential
      operationId: Node_Credential_get
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node.Credential/v1/list:
    get:
      tags:
        - DR.Node
      summary: Return list for SYNO.DR.Node.Credential
      operationId: Node_Credential_list
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node.Credential/v1/relay:
    get:
      tags:
        - DR.Node
      summary: Return relay for SYNO.DR.Node.Credential
      operationId: Node_Credential_relay
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node.Credential/v1/reverse_create:
    get:
      tags:
        - DR.Node
      summary: Return reverse_create for SYNO.DR.Node.Credential
      operationId: Node_Credential_reverse_create
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node.Credential/v1/test_create:
    get:
      tags:
        - DR.Node
      summary: Return test_create for SYNO.DR.Node.Credential
      operationId: Node_Credential_test_create
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node.Credential/v1/test_reverse_create:
    get:
      tags:
        - DR.Node
      summary: Return test_reverse_create for SYNO.DR.Node.Credential
      operationId: Node_Credential_test_reverse_create
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node.Credential/v1/test_set:
    get:
      tags:
        - DR.Node
      summary: Return test_set for SYNO.DR.Node.Credential
      operationId: Node_Credential_test_set
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node.Credential/v1/temp_create:
    get:
      tags:
        - DR.Node
      summary: Return temp_create for SYNO.DR.Node.Credential
      operationId: Node_Credential_temp_create
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node.Credential/v1/temp_reverse_create:
    get:
      tags:
        - DR.Node
      summary: Return temp_reverse_create for SYNO.DR.Node.Credential
      operationId: Node_Credential_temp_reverse_create
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node.Credential/v1/delete:
    get:
      tags:
        - DR.Node
      summary: Return delete for SYNO.DR.Node.Credential
      operationId: Node_Credential_delete
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DR.Node.Session/v2/create:
    get:
      tags:
        - DR.Node
      summary: Return create for SYNO.DR.Node.Session
      operationId: Node_Session_create
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
